project:
  type: website

website:
  title: "Cracking Data with Yang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yangrchen
  repo-url: https://github.com/yangrchen/cracking-data-yang
  repo-actions: [issue]
format:
  html:
    highlight-style: dracula
    theme:
      light: flatly
      dark: darkly 
    css: styles.css

editor: 
  render-on-save: true