project:
  type: website

website:
  title: "Cracking Data with Yang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yangrchen
format:
  html:
    theme:
      light: flatly
      dark: darkly 
    css: styles.css

editor: 
  render-on-save: true